import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Roboto, Poppins } from "next/font/google";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer"
import { ThemeProvider } from "../app/context/ThemeContext";
import AuthProvider from "./components/AuthProvider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body >
       
          <ThemeProvider>
            <AuthProvider>
               <div className="container">
                <Navbar/>
                {children}
                <Footer/>
                </div>
            </AuthProvider>
          </ThemeProvider>
       
        
        
        </body>
    </html>
  );
}
